version: '3.1'

services:

  mariadb:
    container_name: unifi_phd-mdb
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - database-data:/var/lib/mysql
      - ../sql:/sql

  adminer:
    container_name: adm
    image: adminer
    restart: always
    ports:
      - 8080:8080

  php:
    container_name: php
    image: php:7-fpm-alpine
    links:
      - mariadb:database

volumes:
  database-data: